apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJsb2hhbml1bWVzaC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYkc5b1lXNXBkVzFsYzJoQVoyMWhhV3d1WTI5dE9rcGhia0F5TURJeiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
